// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CAS.FinancePortal.Web.Server.Core.Models.Entities.SuperApplication.Tables;
using CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables;

namespace CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Views;

public partial class VwCombinedUserInformation
{
    public int UserId { get; set; }

    public string UserEmail { get; set; }

    public int UserType { get; set; }

    public string Password { get; set; }

    public bool IsActive { get; set; }

    public bool IsLockOut { get; set; }

    public int LoginAttemps { get; set; }

    public int UserReferenceId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
	public int DepartmentId { get; set; }

   public virtual UserAccess UserAccess { get; set; }

}