// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


public partial class VwDepartment
{
    public int Id { get; set; }
    public int DepartmentGroupId { get; set; }

    public string DepartmentName { get; set; }

    public string Alias { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? WeekStart { get; set; }

    public string Timezone { get; set; }

    public string TimeDifferenceMnl { get; set; }
}
