// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class VwEmployee
{
    public int EmployeeId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int DepartmentId { get; set; }

    public string CompanyEmail { get; set; }

    public string MobileNo { get; set; }

    public string Tin { get; set; }

    public string Gender { get; set; }

    public DateOnly DateHired { get; set; }

    public string YearId { get; set; }

    public bool IsActive { get; set; }
}