// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Views;

public partial class VwStaffing
{
    public int Id { get; set; }

    public int? EmployeeId { get; set; }

    public DateTime ShiftDate { get; set; }

    public DateTime? ShiftStart { get; set; }

    public DateTime? ShiftEnd { get; set; }

    public DateTime? ClockIn { get; set; }

    public DateTime? ClockOut { get; set; }

    public TimeSpan? Late { get; set; }

    public TimeSpan? Undertime { get; set; }

    public string Tag { get; set; }
}