// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


public partial class VwUserDetail
{
    public bool? IsActive { get; set; }

    public string YearId { get; set; }

    public int EmployeeId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string MiddleNamePrefix { get; set; }

    public string Gender { get; set; }

    public string Salutation { get; set; }

    public DateOnly DateHired { get; set; }

    public string EmploymentStatus { get; set; }

    public string CompanyEmail { get; set; }
}