// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class ApplicationSetting
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

    public bool IsActive { get; set; }
}