// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CAS.FinancePortal.Web.Server.Core.Models.Entities.SuperApplication.Tables;


public partial class CoreSystemAccess
{
    public int Id { get; set; }

    public int SystemId { get; set; }

    public int UserId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsActive { get; set; }

    public virtual CoreSystem System { get; set; }

    public virtual LoginCredential User { get; set; }
}