// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


public partial class CoreSystem
{
    public int SystemId { get; set; }

    public string SystemName { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string SystemUrl { get; set; }
    public string Description { get; set; }
    public string SystemIcon { get; set; }

    public virtual ICollection<CoreSystemAccess> CoreSystemAccesses { get; set; } = new List<CoreSystemAccess>();
}