// <auto-generated />
using System;
using CAS.FinancePortal.Web.Server.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAS.FinancePortal.Web.Server.Persistence.Migrations.CurrentApplication
{
    [DbContext(typeof(CurrentApplicationDbContext))]
    [Migration("20260523013159_InitialLocalSchema")]
    partial class InitialLocalSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.SystemMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsParent")
                        .HasColumnType("bit")
                        .HasColumnName("is_parent");

                    b.Property<bool?>("IsSubParent")
                        .HasColumnType("bit")
                        .HasColumnName("is_sub_parent");

                    b.Property<string>("MenuIcon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_icon");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_name");

                    b.Property<string>("MenuPath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_path");

                    b.Property<int?>("OrderBy")
                        .HasColumnType("int")
                        .HasColumnName("order_by");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int>("UserAccessTypeId")
                        .HasColumnType("int")
                        .HasColumnName("user_access_type_id");

                    b.HasKey("Id");

                    b.HasIndex("UserAccessTypeId");

                    b.ToTable("system_menus", (string)null);
                });

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.UserAccess", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("UserAccessId")
                        .HasColumnType("int")
                        .HasColumnName("user_access_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_user_access_1");

                    b.HasAlternateKey("UserId")
                        .HasName("AK_user_access_user_id");

                    b.HasIndex("UserAccessId");

                    b.ToTable("user_access", (string)null);
                });

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.UserAccessType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("access_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("PK_user_access");

                    b.ToTable("user_access_types", (string)null);
                });

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Videos", (string)null);
                });

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Views.VwCombinedUserInformation", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLockOut")
                        .HasColumnType("bit")
                        .HasColumnName("is_lock_out");

                    b.Property<string>("LastName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("last_name");

                    b.Property<int>("LoginAttemps")
                        .HasColumnType("int")
                        .HasColumnName("login_attemps");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_email");

                    b.Property<int>("UserReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("user_reference_id");

                    b.Property<int>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("user_type");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("vw_combined_user_informations", (string)null);
                });

            modelBuilder.Entity("Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Esignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ESignature");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("VwDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentGroupId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TimeDifferenceMnl")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("WeekStart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vw_Departments", (string)null);
                });

            modelBuilder.Entity("VwEmployee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DateHired")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TIN");

                    b.Property<string>("YearId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Vw_Employees", (string)null);
                });

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.SystemMenu", b =>
                {
                    b.HasOne("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.UserAccessType", "UserAccessType")
                        .WithMany("SystemMenus")
                        .HasForeignKey("UserAccessTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_system_menus_user_access_types");

                    b.Navigation("UserAccessType");
                });

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.UserAccess", b =>
                {
                    b.HasOne("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.UserAccessType", "UserAccessNavigation")
                        .WithMany("UserAccesses")
                        .HasForeignKey("UserAccessId")
                        .IsRequired()
                        .HasConstraintName("FK_user_access_user_access_types");

                    b.Navigation("UserAccessNavigation");
                });

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.Video", b =>
                {
                    b.HasOne("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.UserAccess", "UploadedByUserAccess")
                        .WithMany("Videos")
                        .HasForeignKey("UploadedBy")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Videos_user_access_user_id");

                    b.Navigation("UploadedByUserAccess");
                });

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Views.VwCombinedUserInformation", b =>
                {
                    b.HasOne("VwDepartment", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_vw_combined_user_informations_Vw_Departments");

                    b.HasOne("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.UserAccess", "UserAccess")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccess");
                });

            modelBuilder.Entity("Signature", b =>
                {
                    b.HasOne("VwEmployee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Signatures_Vw_Employees");
                });

            modelBuilder.Entity("VwEmployee", b =>
                {
                    b.HasOne("VwDepartment", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Vw_Employees_Vw_Departments");
                });

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.UserAccess", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables.UserAccessType", b =>
                {
                    b.Navigation("SystemMenus");

                    b.Navigation("UserAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
