// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


public partial class AssetHistory
{
    public int Id { get; set; }

    public int AssetId { get; set; }

    public int AssetHistoryStatusId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public string Remarks { get; set; }

    public virtual Asset Asset { get; set; }

    public virtual ICollection<AssetEmployeeHistory> AssetEmployeeHistories { get; set; } = new List<AssetEmployeeHistory>();

    public virtual AssetHistoryStatus AssetHistoryStatus { get; set; }
}