﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class AssetType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public bool IsAccessory { get; set; }

    public string Remarks { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<Asset> Assets { get; set; } = new List<Asset>();
}
