﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class AssetAccountabilityItem
{
    public int Id { get; set; }

    public int ApfId { get; set; }

    public int AssetId { get; set; }

    public string Remarks { get; set; }

    public virtual AssetAccountability Apf { get; set; }

    public virtual Asset Asset { get; set; }
}
