// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class Asset
{
    public int Id { get; set; }

    public int AssetTypeId { get; set; }

    public int? AccessoryTypeId { get; set; }

    public string SerialNumber { get; set; }

    public int StatusId { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public int VendorId { get; set; }

    public DateOnly PurchasedDate { get; set; }

    public DateOnly? WarrantyDate { get; set; }

    public int? UsefulLife { get; set; }

    public decimal? PurchasedAmount { get; set; }

    public string ReceiptNumber { get; set; }

    public bool IsClientOwner { get; set; }

    public bool IsCompanyOwner { get; set; }

    public bool IsRental { get; set; }

    public int? ParentId { get; set; }

    public int? PurchaseOrderId { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsActive { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual AccessoryType AccessoryType { get; set; }

    public virtual ICollection<AssetAccountabilityItem> AssetAccountabilityItems { get; set; } = new List<AssetAccountabilityItem>();

    public virtual AssetType AssetType { get; set; }

    public virtual PurchaseOrder PurchaseOrder { get; set; }

    public virtual AssetStatus Status { get; set; }

    public virtual VendorProfile Vendor { get; set; }
}
