﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class AssetDeployment
{
    public int Id { get; set; }

    public int? StationId { get; set; }

    public int AssetId { get; set; }

    public bool IsActive { get; set; }

    public string Remarks { get; set; }

    public int? WfhEmployeeId { get; set; }

    public virtual Asset Asset { get; set; }

    public virtual Station Station { get; set; }
}
