// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class AssetService
{
    public int Id { get; set; }

    public int AssetId { get; set; }

    public decimal? LaborCost { get; set; }

    public decimal PartsCost { get; set; }

    public string Description { get; set; }

    public DateOnly CompletedDate { get; set; }

    public string ServicedBy { get; set; }

    public DateOnly ServicedDate { get; set; }

    public int AssetServiceTypeId { get; set; }

    public string Remarks { get; set; }

    public virtual Asset Asset { get; set; }

    public virtual AssetServicesType AssetServiceType { get; set; }
}
