// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


public partial class AssetEmployeeHistory
{
    public int Id { get; set; }

    public int AssetHistoryId { get; set; }

    public int AssignedEmployeeId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public string Remarks { get; set; }

    public virtual AssetHistory AssetHistory { get; set; }
}