
﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class Cluster
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int OfficeId { get; set; }

    public bool IsActive { get; set; }



    public int PosX { get; set; }

    public int PosY { get; set; }

    public int ContainerHeight { get; set; }

    public int ContainerWidth { get; set; }

    public string Remarks { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Office Office { get; set; }

    public virtual ICollection<Station> Stations { get; set; } = new List<Station>();
}
