// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;



namespace CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables;

public partial class Department
{
    public int Id { get; set; }

    public int DepartmentTypeId { get; set; }

    public string DepartmentName { get; set; }

    public string Alias { get; set; }

    public bool IsActive { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? WeekStart { get; set; }

    public string Timezone { get; set; }

    public int? TimeDifferenceMnl { get; set; }
}
