// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;



namespace CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables;

public partial class Employee
{
    public int Id { get; set; }

    public string EmployeeId { get; set; }

    public string YearId { get; set; }

    public bool IsActive { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string CompanyEmail { get; set; }

    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public DateOnly DateHired { get; set; }

    public string Gender { get; set; }

    public string Tin { get; set; }

    public int? TeamId { get; set; }

    public string TeamName { get; set; }

    public string MobileNo { get; set; }

    public string ImmediateSuperior { get; set; }
}
