// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


public partial class Office
{
    public int Id { get; set; }

    public string OfficeName { get; set; }

    public int LocationId { get; set; }

    public bool IsActive { get; set; }

    public string Remarks { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<Cluster> Clusters { get; set; } = new List<Cluster>();

    public virtual Location Location { get; set; }
}