﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class PurchaseOrder
{
    public int Id { get; set; }

    public int RequestId { get; set; }

    public DateTime OrderDate { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public decimal DiscountAmount { get; set; }

    public string SpecialInstruction { get; set; }

    public bool IsActive { get; set; }

    public bool? IsApprove { get; set; }

    public int? ApprovedBy { get; set; }

    public DateTime? ApproveDate { get; set; }

    public int? ApproveSignatureId { get; set; }

    public string ApproverNotes { get; set; }

    public string ContactPerson { get; set; }

    public int ShippingId { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public bool CanModify { get; set; }

    public virtual ICollection<Asset> Assets { get; set; } = new List<Asset>();

    public virtual RequestForm Request { get; set; }

    public virtual Location Shipping { get; set; }
}
