﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class RequestForm
{
    public int Id { get; set; }

    public int RequestorId { get; set; }

    public int LocationId { get; set; }

    public int VendorId { get; set; }

    public int RequestTypeId { get; set; }

    public DateTime RequestDate { get; set; }

    public DateOnly DueDate { get; set; }

    public string Purpose { get; set; }

    public string SpecialInstruction { get; set; }
    public bool IsActive { get; set; }

    public bool? IsReview { get; set; }

    public int? ReviewBy { get; set; }

    public int? ReviewSignatureId { get; set; }

    public DateTime? ReviewDate { get; set; }

    public string ReviewNotes { get; set; }

    public bool? IsApprove { get; set; }

    public int? ApprovedBy { get; set; }

    public int? ApproveSignatureId { get; set; }

    public DateTime? ApproveDate { get; set; }

    public int TaxBasisId { get; set; }

    public string ChequeNumber { get; set; }

    public bool CanModify { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public virtual Signature ApproveSignature { get; set; }

    public virtual Location Location { get; set; }

    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();

    public virtual ICollection<RequestItem> RequestItems { get; set; } = new List<RequestItem>();

    public virtual RequestType RequestType { get; set; }

    public virtual Signature ReviewSignature { get; set; }

    public virtual TaxBasis TaxBasis { get; set; }

    public virtual VendorProfile Vendor { get; set; }
}
