// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class RequestType
{
    public int Id { get; set; }

    public string Type { get; set; }

    public string Remarks { get; set; }

    public bool IsActive { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<RequestForm> RequestForms { get; set; } = new List<RequestForm>();
}
