// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class RequestItem
{
    public int Id { get; set; }

    public int RequestFormId { get; set; }

    public int Qty { get; set; }

    public string Unit { get; set; }

    public string ItemDescription { get; set; }
    
    public string Brand { get; set; }

    public string Model { get; set; }

    public decimal UnitPrice { get; set; }

    public int TaxTypeId { get; set; }

    public int WithholdingTaxTypeId { get; set; }

    public decimal TotalAmount { get; set; }

    public virtual RequestForm RequestForm { get; set; }

    public virtual TaxType TaxType { get; set; }

    public virtual WithholdingTaxType WithholdingTaxType { get; set; }
}
