﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class SeatAssignment
{
    public int Id { get; set; }

    public int StationId { get; set; }

    public int EmployeeId { get; set; }

    public DateTime AssignedDate { get; set; }

    public DateTime? VacatedDate { get; set; }

    public bool IsActive { get; set; }

    public string Remarks { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsApfGenerated { get; set; }

    public virtual Station Station { get; set; }
}
