﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class Signature
{
    public int Id { get; set; }

    public int EmployeeId { get; set; }

    public string Esignature { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<AssetAccountability> AssetAccountabilityAdminSignatures { get; set; } = new List<AssetAccountability>();

    public virtual ICollection<AssetAccountability> AssetAccountabilityEmployeeSignatures { get; set; } = new List<AssetAccountability>();

    public virtual ICollection<AssetAccountability> AssetAccountabilitySupervisorSignatures { get; set; } = new List<AssetAccountability>();

    public virtual ICollection<AssetAccountability> AssetAccountabilityTechnicalSignatures { get; set; } = new List<AssetAccountability>();

    public virtual ICollection<RequestForm> RequestFormApproveSignatures { get; set; } = new List<RequestForm>();

    public virtual ICollection<RequestForm> RequestFormReviewSignatures { get; set; } = new List<RequestForm>();
}
