﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class Station
{
    public int Id { get; set; }

    public string Station1 { get; set; }

    public int ClusterId { get; set; }

    public bool IsActive { get; set; }

    public string Remarks { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<AssetDeployment> AssetDeployments { get; set; } = new List<AssetDeployment>();

    public virtual Cluster Cluster { get; set; }

    public virtual ICollection<SeatAssignment> SeatAssignments { get; set; } = new List<SeatAssignment>();
}
