// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables;

public partial class SystemMenu
{
	public int Id { get; set; }

	public int UserAccessTypeId { get; set; }

	public string MenuName { get; set; }

	public string MenuPath { get; set; }

	public string MenuIcon { get; set; }

	public int? ParentId { get; set; }

	public bool? IsParent { get; set; }

	public bool? IsSubParent { get; set; }

	public int? OrderBy { get; set; }

	public virtual UserAccessType UserAccessType { get; set; }
}