// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


public partial class TaxType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal NetOfVat { get; set; }

    public decimal Vat { get; set; }

    public int TaxBasisId { get; set; }

    public bool IsActive { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string Remarks { get; set; }

    public virtual ICollection<RequestItem> RequestItems { get; set; } = new List<RequestItem>();

    public virtual TaxBasis TaxBasis { get; set; }
}
