// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables;

public partial class UserAccessType
{
	public int Id { get; set; }

	public string AccessType { get; set; }

	public bool IsActive { get; set; }

	public virtual ICollection<SystemMenu> SystemMenus { get; set; } = new List<SystemMenu>();

	public virtual ICollection<UserAccess> UserAccesses { get; set; } = new List<UserAccess>();
}