// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace CAS.FinancePortal.Web.Server.Core.Models.Entities.CurrentApplication.Tables;

public partial class UserAccess
{
	public int Id { get; set; }

	public int UserId { get; set; }

	public int UserAccessId { get; set; }

	public bool IsActive { get; set; }

	public int CreatedBy { get; set; }

	public DateTime CreatedDate { get; set; }

	public virtual UserAccessType UserAccessNavigation { get; set; }
	public virtual ICollection<Video> Videos { get; set; } = new List<Video>();
}