// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

public partial class VendorProfile
{
    public int Id { get; set; }

    public string CompanyName { get; set; }

    public string Address { get; set; }

    public string ContactPerson { get; set; }

    public string ContactNo { get; set; }

    public string EmailAddress { get; set; }

    public string Bank { get; set; }

    public string BankAccountName { get; set; }

    public string BankAccountNumber { get; set; }

    public string Tin { get; set; }
    
    public string ChequeName { get; set; }

    public string Remarks { get; set; }

    public bool IsActive { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ICollection<Asset> Assets { get; set; } = new List<Asset>();

    public virtual ICollection<RequestForm> RequestForms { get; set; } = new List<RequestForm>();
}